Create cs.po
cooljeanius/The_Earths_Gut pull request #50
Opened 2023-08-20 15:37 UTC by MultiSeptim

My first step to the czech translation of this campaign (as you wished some time ago). I have a little more time now, so I have decided to take this task. I am not sure how quickly I will able to work on it, I prefer to translate more aNO for example, but be sure I will work on it. Slowly but surely...

@celerini it would be nice if you could check it, please.

2023-08-20 15:46 UTC, MultiSeptim commented
And some units from this campaign (e.g. some Woses) are included in mainline now...

2023-08-20 20:42 UTC, cooljeanius commented
> And some units from this campaign (e.g. some Woses) are included in mainline now...

oh yeah I think @Konrad22 was pointing that out, too...

2023-08-21 21:38 UTC, celerini requested changes
great work, @MultiSeptim

2023-08-21 21:38 UTC, celerini commented on translations/wesnoth-The_Earths_Gut/cs.po
> +"jeskynních a houbových terénem ji pohyb stojí o 1 pohybový bod méně a její "
```suggestion
"jeskynních a houbových terénech ji pohyb stojí o 1 pohybový bod méně a její "
```

2023-08-21 21:38 UTC, celerini commented on translations/wesnoth-The_Earths_Gut/cs.po
> +msgstr "řemdich"
```suggestion
msgstr "řemdih"
```

2023-08-21 21:38 UTC, celerini commented on translations/wesnoth-The_Earths_Gut/cs.po
> +"Piráti, kteří tvoří posádu těchto lodí, jsou více než rádi, když mohou "
```suggestion
"Piráti, kteří tvoří posádku těchto lodí, jsou více než rádi, když mohou "
```

2023-08-21 21:38 UTC, celerini commented on translations/wesnoth-The_Earths_Gut/cs.po
> +msgstr "Rychle, Hameli!"
```suggestion
msgstr "Rychle, Hamele!"
```

2023-08-21 21:38 UTC, celerini commented on translations/wesnoth-The_Earths_Gut/cs.po
> +msgstr "Musí být nějaká jiná cesta, buď na sever nebo na jih."
```suggestion
msgstr "Musí být nějaká jiná cesta, buď na sever, nebo na jih."
```

2023-08-21 21:38 UTC, celerini commented on translations/wesnoth-The_Earths_Gut/cs.po
> +"bohatství Trpasličích Dveří a přísahali, že ho získají pro sebe. Obyvatelé "
```suggestion
"bohatství Trpasličích Dveří a přísahaly, že ho získají pro sebe. Obyvatelé "
```

2023-08-21 21:38 UTC, celerini commented on translations/wesnoth-The_Earths_Gut/cs.po
> +"jen málokdo odvážil následovat."
```suggestion
"jen málokdo odvážil je následovat."
```

2023-08-22 11:39 UTC, MultiSeptim commented
Ready to merge.

2023-08-22 11:58 UTC, merged